import {
  ChurchEvent,
  Team,
  Person,
  Registration,
  AttendanceRecord,
  Game,
  AdminUser,
  ChurchSettings,
} from "@/types/dashboard";

export const INITIAL_EVENTS: ChurchEvent[] = [
  {
    id: "evt-1",
    name: "Youth Conference 2026: IGNITE",
    category: "Conference",
    startDate: "2026-07-28T09:00:00Z",
    endDate: "2026-07-30T21:00:00Z",
    location: "Main Auditorium & Recreation Center",
    capacity: 1500,
    registeredCount: 1248,
    checkedInCount: 892,
    status: "Live",
    registrationDeadline: "2026-07-27T23:59:59Z",
    teamAssignmentEnabled: true,
    description:
      "Annual 3-day Youth Conference featuring worship, guest speakers, team games, and workshops.",
  },
  {
    id: "evt-2",
    name: "Worship Night: Encounter",
    category: "Worship Service",
    startDate: "2026-08-14T19:00:00Z",
    endDate: "2026-08-14T22:00:00Z",
    location: "Grace City Worship Hall",
    capacity: 800,
    registeredCount: 420,
    checkedInCount: 0,
    status: "Upcoming",
    registrationDeadline: "2026-08-13T23:59:59Z",
    teamAssignmentEnabled: false,
    description:
      "An extended evening of prayer, prophetic worship, and acoustic sessions for all ages.",
  },
  {
    id: "evt-3",
    name: "Volunteer & Leaders Summit",
    category: "Training",
    startDate: "2026-09-05T09:00:00Z",
    endDate: "2026-09-05T16:00:00Z",
    location: "Conference Room A & B",
    capacity: 250,
    registeredCount: 185,
    checkedInCount: 0,
    status: "Upcoming",
    registrationDeadline: "2026-09-01T23:59:59Z",
    teamAssignmentEnabled: false,
    description:
      "Equipping church leadership teams, group facilitators, and event staff for Fall 2026.",
  },
  {
    id: "evt-4",
    name: "Youth Summer Camp 2025",
    category: "Retreat",
    startDate: "2025-07-15T08:00:00Z",
    endDate: "2025-07-18T18:00:00Z",
    location: "Pinecrest Mountain Lodge",
    capacity: 600,
    registeredCount: 592,
    checkedInCount: 588,
    status: "Completed",
    registrationDeadline: "2025-07-10T23:59:59Z",
    teamAssignmentEnabled: true,
    description:
      "Summer outdoor retreat with lake activities, night bonfires, and team competitions.",
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: "team-tempest",
    name: "Team Tempest",
    color: "Electric Cyan",
    colorHex: "#06B6D4",
    captain: "Sarah Jenkins",
    captainPhone: "+1 (555) 234-5678",
    memberCount: 314,
    totalPoints: 1620,
    badgeIcon: "Zap",
  },
  {
    id: "team-lumin",
    name: "Team Lumin",
    color: "Golden Amber",
    colorHex: "#F59E0B",
    captain: "Grace Chen",
    captainPhone: "+1 (555) 345-6789",
    memberCount: 312,
    totalPoints: 1510,
    badgeIcon: "Sun",
  },
  {
    id: "team-igniter",
    name: "Team Igniter",
    color: "Crimson Red",
    colorHex: "#EF4444",
    captain: "Marcus Vance",
    captainPhone: "+1 (555) 123-4567",
    memberCount: 312,
    totalPoints: 1450,
    badgeIcon: "Flame",
  },
  {
    id: "team-valor",
    name: "Team Valor",
    color: "Emerald Green",
    colorHex: "#10B981",
    captain: "David Kalu",
    captainPhone: "+1 (555) 456-7890",
    memberCount: 310,
    totalPoints: 1380,
    badgeIcon: "Shield",
  },
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: "reg-001",
    registrationNumber: "YC26-1001",
    personId: "p-101",
    name: "Jordan Miller",
    phone: "+1 (555) 987-6543",
    email: "jordan.m@gmail.com",
    gender: "Male",
    membershipStatus: "Member",
    assignedTeamId: "team-tempest",
    assignedTeamName: "Team Tempest",
    assignedTeamColor: "#06B6D4",
    qrCodeUrl:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=YC26-1001",
    qrGenerated: true,
    status: "Checked-In",
    confirmationSent: true,
    registeredAt: "2026-07-02T14:20:00Z",
    checkedInAt: "2026-07-28T08:45:12Z",
  },
  {
    id: "reg-002",
    registrationNumber: "YC26-1002",
    personId: "p-102",
    name: "Chloe Bennett",
    phone: "+1 (555) 876-5432",
    email: "chloe.b@outlook.com",
    gender: "Female",
    membershipStatus: "Visitor",
    assignedTeamId: "team-lumin",
    assignedTeamName: "Team Lumin",
    assignedTeamColor: "#F59E0B",
    qrCodeUrl:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=YC26-1002",
    qrGenerated: true,
    status: "Checked-In",
    confirmationSent: true,
    registeredAt: "2026-07-03T11:15:00Z",
    checkedInAt: "2026-07-28T08:52:40Z",
  },
  {
    id: "reg-003",
    registrationNumber: "YC26-1003",
    personId: "p-103",
    name: "Alex Rivera",
    phone: "+1 (555) 765-4321",
    email: "alex.rivera@yahoo.com",
    gender: "Male",
    membershipStatus: "Member",
    assignedTeamId: "team-igniter",
    assignedTeamName: "Team Igniter",
    assignedTeamColor: "#EF4444",
    qrCodeUrl:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=YC26-1003",
    qrGenerated: true,
    status: "Checked-In",
    confirmationSent: true,
    registeredAt: "2026-07-05T16:40:00Z",
    checkedInAt: "2026-07-28T09:01:05Z",
  },
  {
    id: "reg-004",
    registrationNumber: "YC26-1004",
    personId: "p-104",
    name: "Daniel Kim",
    phone: "+1 (555) 654-3210",
    email: "dkim99@gmail.com",
    gender: "Male",
    membershipStatus: "Visitor",
    assignedTeamId: "team-valor",
    assignedTeamName: "Team Valor",
    assignedTeamColor: "#10B981",
    qrCodeUrl:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=YC26-1004",
    qrGenerated: true,
    status: "Confirmed",
    confirmationSent: true,
    registeredAt: "2026-07-08T09:30:00Z",
  },
  {
    id: "reg-005",
    registrationNumber: "YC26-1005",
    personId: "p-105",
    name: "Hannah Wright",
    phone: "+1 (555) 543-2109",
    email: "hannah.wright@icloud.com",
    gender: "Female",
    membershipStatus: "Member",
    assignedTeamId: "team-tempest",
    assignedTeamName: "Team Tempest",
    assignedTeamColor: "#06B6D4",
    qrCodeUrl:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=YC26-1005",
    qrGenerated: true,
    status: "Checked-In",
    confirmationSent: true,
    registeredAt: "2026-07-10T15:10:00Z",
    checkedInAt: "2026-07-28T09:12:18Z",
  },
  {
    id: "reg-006",
    registrationNumber: "YC26-1006",
    personId: "p-106",
    name: "Caleb Foster",
    phone: "+1 (555) 432-1098",
    email: "caleb.foster@gmail.com",
    gender: "Male",
    membershipStatus: "Visitor",
    assignedTeamId: "team-lumin",
    assignedTeamName: "Team Lumin",
    assignedTeamColor: "#F59E0B",
    qrCodeUrl:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=YC26-1006",
    qrGenerated: true,
    status: "Confirmed",
    confirmationSent: true,
    registeredAt: "2026-07-12T18:25:00Z",
  },
  {
    id: "reg-007",
    registrationNumber: "YC26-1007",
    personId: "p-107",
    name: "Maya Patel",
    phone: "+1 (555) 321-0987",
    email: "maya.patel@hotmail.com",
    gender: "Female",
    membershipStatus: "Member",
    assignedTeamId: "team-igniter",
    assignedTeamName: "Team Igniter",
    assignedTeamColor: "#EF4444",
    qrCodeUrl:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=YC26-1007",
    qrGenerated: true,
    status: "Checked-In",
    confirmationSent: true,
    registeredAt: "2026-07-14T10:05:00Z",
    checkedInAt: "2026-07-28T09:18:50Z",
  },
  {
    id: "reg-008",
    registrationNumber: "YC26-1008",
    personId: "p-108",
    name: "Liam Taylor",
    phone: "+1 (555) 210-9876",
    email: "liam.taylor@gmail.com",
    gender: "Male",
    membershipStatus: "Member",
    assignedTeamId: "team-valor",
    assignedTeamName: "Team Valor",
    assignedTeamColor: "#10B981",
    qrCodeUrl:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=YC26-1008",
    qrGenerated: true,
    status: "Checked-In",
    confirmationSent: true,
    registeredAt: "2026-07-15T13:45:00Z",
    checkedInAt: "2026-07-28T09:25:10Z",
  },
];

export const INITIAL_PEOPLE: Person[] = [
  {
    id: "p-101",
    name: "Jordan Miller",
    phone: "+1 (555) 987-6543",
    email: "jordan.m@gmail.com",
    gender: "Male",
    dob: "2008-04-12",
    membershipStatus: "Member",
    registrationHistoryCount: 3,
    departmentsPlaceholder: ["Youth Choir", "Audio Visual Team"],
    attendanceHistoryPlaceholder: [
      {
        eventName: "Youth Conference 2026",
        date: "2026-07-28",
        attended: true,
      },
      {
        eventName: "Youth Summer Camp 2025",
        date: "2025-07-15",
        attended: true,
      },
      {
        eventName: "Youth Winter Retreat 2024",
        date: "2024-12-10",
        attended: true,
      },
    ],
    notesPlaceholder: "Allergic to peanuts. Prefers front-row seating.",
  },
  {
    id: "p-102",
    name: "Chloe Bennett",
    phone: "+1 (555) 876-5432",
    email: "chloe.b@outlook.com",
    gender: "Female",
    dob: "2009-11-20",
    membershipStatus: "Visitor",
    registrationHistoryCount: 1,
    departmentsPlaceholder: ["First Time Guest"],
    attendanceHistoryPlaceholder: [
      {
        eventName: "Youth Conference 2026",
        date: "2026-07-28",
        attended: true,
      },
    ],
    notesPlaceholder:
      "Invited by Hannah Wright. Expressed interest in Joining Student Ministry.",
  },
  {
    id: "p-103",
    name: "Alex Rivera",
    phone: "+1 (555) 765-4321",
    email: "alex.rivera@yahoo.com",
    gender: "Male",
    dob: "2007-09-05",
    membershipStatus: "Member",
    registrationHistoryCount: 4,
    departmentsPlaceholder: ["Youth Worship Band", "Ushering"],
    attendanceHistoryPlaceholder: [
      {
        eventName: "Youth Conference 2026",
        date: "2026-07-28",
        attended: true,
      },
      {
        eventName: "Youth Summer Camp 2025",
        date: "2025-07-15",
        attended: true,
      },
    ],
    notesPlaceholder: "Guitarist in the high school worship group.",
  },
  {
    id: "p-104",
    name: "Daniel Kim",
    phone: "+1 (555) 654-3210",
    email: "dkim99@gmail.com",
    gender: "Male",
    dob: "2008-01-30",
    membershipStatus: "Visitor",
    registrationHistoryCount: 2,
    departmentsPlaceholder: ["Sports Ministry"],
    attendanceHistoryPlaceholder: [
      {
        eventName: "Youth Conference 2026",
        date: "2026-07-28",
        attended: false,
      },
    ],
    notesPlaceholder: "Basketball team captain at Westside High.",
  },
];

export const INITIAL_ATTENDANCE_LOG: AttendanceRecord[] = [
  {
    id: "att-1",
    registrationId: "reg-008",
    registrationNumber: "YC26-1008",
    attendeeName: "Liam Taylor",
    teamName: "Team Valor",
    teamColor: "#10B981",
    time: "09:25:10 AM",
    checkedInBy: "Mark Higgins (Desk 2)",
    method: "QR Scan",
  },
  {
    id: "att-2",
    registrationId: "reg-007",
    registrationNumber: "YC26-1007",
    attendeeName: "Maya Patel",
    teamName: "Team Igniter",
    teamColor: "#EF4444",
    time: "09:18:50 AM",
    checkedInBy: "Elena Rostova (Desk 1)",
    method: "QR Scan",
  },
  {
    id: "att-3",
    registrationId: "reg-005",
    registrationNumber: "YC26-1005",
    attendeeName: "Hannah Wright",
    teamName: "Team Tempest",
    teamColor: "#06B6D4",
    time: "09:12:18 AM",
    checkedInBy: "Mark Higgins (Desk 2)",
    method: "Manual Search",
  },
  {
    id: "att-4",
    registrationId: "reg-003",
    registrationNumber: "YC26-1003",
    attendeeName: "Alex Rivera",
    teamName: "Team Igniter",
    teamColor: "#EF4444",
    time: "09:01:05 AM",
    checkedInBy: "Elena Rostova (Desk 1)",
    method: "QR Scan",
  },
  {
    id: "att-5",
    registrationId: "reg-002",
    registrationNumber: "YC26-1002",
    attendeeName: "Chloe Bennett",
    teamName: "Team Lumin",
    teamColor: "#F59E0B",
    time: "08:52:40 AM",
    checkedInBy: "Mark Higgins (Desk 2)",
    method: "QR Scan",
  },
];

export const INITIAL_GAMES: Game[] = [
  {
    id: "gm-1",
    title: "Dodgeball Smash Championship",
    category: "Arena Games",
    maxPoints: 500,
    order: 1,
    status: "Completed",
    winnerTeamId: "team-tempest",
    scores: [
      { teamId: "team-tempest", teamName: "Team Tempest", points: 500 },
      { teamId: "team-lumin", teamName: "Team Lumin", points: 350 },
      { teamId: "team-igniter", teamName: "Team Igniter", points: 250 },
      { teamId: "team-valor", teamName: "Team Valor", points: 200 },
    ],
  },
  {
    id: "gm-2",
    title: "Mega Tug-of-War Showdown",
    category: "Outdoor Field",
    maxPoints: 400,
    order: 2,
    status: "Completed",
    winnerTeamId: "team-lumin",
    scores: [
      { teamId: "team-lumin", teamName: "Team Lumin", points: 400 },
      { teamId: "team-tempest", teamName: "Team Tempest", points: 300 },
      { teamId: "team-igniter", teamName: "Team Igniter", points: 300 },
      { teamId: "team-valor", teamName: "Team Valor", points: 200 },
    ],
  },
  {
    id: "gm-3",
    title: "Bible Trivia Blitz",
    category: "Auditorium Quiz",
    maxPoints: 300,
    order: 3,
    status: "Completed",
    winnerTeamId: "team-igniter",
    scores: [
      { teamId: "team-igniter", teamName: "Team Igniter", points: 300 },
      { teamId: "team-tempest", teamName: "Team Tempest", points: 250 },
      { teamId: "team-valor", teamName: "Team Valor", points: 250 },
      { teamId: "team-lumin", teamName: "Team Lumin", points: 200 },
    ],
  },
  {
    id: "gm-4",
    title: "Giant Inflatable Obstacle Relay",
    category: "Outdoor Field",
    maxPoints: 600,
    order: 4,
    status: "In Progress",
    scores: [
      { teamId: "team-valor", teamName: "Team Valor", points: 450 },
      { teamId: "team-tempest", teamName: "Team Tempest", points: 400 },
      { teamId: "team-igniter", teamName: "Team Igniter", points: 350 },
      { teamId: "team-lumin", teamName: "Team Lumin", points: 300 },
    ],
  },
  {
    id: "gm-5",
    title: "Capture the Flag Night Battle",
    category: "Campus Wide",
    maxPoints: 500,
    order: 5,
    status: "Upcoming",
    scores: [],
  },
];

export const INITIAL_USERS: AdminUser[] = [
  {
    id: "usr-1",
    name: "Pastor James Wilson",
    email: "jwilson@gracecity.org",
    role: "Super Admin",
    status: "Active",
    lastActive: "Just now",
  },
  {
    id: "usr-2",
    name: "Elena Rostova",
    email: "erostova@gracecity.org",
    role: "Church Admin",
    status: "Active",
    lastActive: "12 minutes ago",
  },
  {
    id: "usr-3",
    name: "Mark Higgins",
    email: "mhiggins@gracecity.org",
    role: "Registration Desk",
    status: "Active",
    lastActive: "5 minutes ago",
  },
  {
    id: "usr-4",
    name: "Chloe Adams",
    email: "cadams@gracecity.org",
    role: "Games Coordinator",
    status: "Active",
    lastActive: "1 hour ago",
  },
];

export const DEFAULT_SETTINGS: ChurchSettings = {
  churchName: "Grace City Church",
  campusName: "Downtown Main Campus",
  address: "742 Evergreen Terrace, Metropolis",
  phone: "+1 (555) 000-1234",
  email: "info@gracecity.org",
  website: "https://gracecity.org",
  branding: {
    primaryColor: "#6366f1",
    logoText: "GRACE CITY EVENTS",
  },
  emailConfig: {
    fromName: "Grace City Youth Events",
    fromEmail: "events@gracecity.org",
    sendConfirmationEmails: true,
    sendReminder24h: true,
  },
  preferences: {
    autoAssignTeams: true,
    requireQrCheckin: true,
    allowSelfRegistration: true,
  },
};
